query executor($executorId: String!) {
  executorByExecutorId(executorId: $executorId) {
    executorId
    description
    httpEndpoint
    apiType
    canValidate
    usesSched
    usesUnits
    missionTplsByExecutorIdList {
      missionTplId
      description
      missionTplAssetClassesByExecutorIdAndMissionTplIdList {
        assetClassName
        assetClassByExecutorIdAndAssetClassName {
          assetsByExecutorIdAndClassNameList {
            assetId
          }
        }
      }
    }
  }
}
