query ($executorId: String!, $missionTplId: String!) {
  missionTplByExecutorIdAndMissionTplId(executorId: $executorId, missionTplId: $missionTplId) {
    missionTplId
    description
    missionTplAssetClassesByExecutorIdAndMissionTplIdList {
      assetClassName
      assetClassByExecutorIdAndAssetClassName {
        description
      }
    }
    parametersByExecutorIdAndMissionTplIdList(orderBy: PARAM_ORDER_ASC) {
      paramName
      type
      required
      defaultValue
      defaultUnits
      description
    }
  }
}
