query missions($executorId: String!, $missionTplId: String!) {
  allMissionsList(condition: {
    executorId: $executorId
    missionTplId: $missionTplId
  }) {
    executorId
    missionTplId
    missionId
    missionStatus
    assetId
    description
    startDate
    endDate
  }
}
