query ($providerId: String!, $missionTplId: String!) {
  missionTplByProviderIdAndMissionTplId(providerId: $providerId, missionTplId: $missionTplId) {
    missionTplId
    description
    missionTplAssetClassesByProviderIdAndMissionTplIdList {
      assetClassName
      assetClassByProviderIdAndAssetClassName {
        description
      }
    }
    parametersByProviderIdAndMissionTplIdList(orderBy: PARAM_ORDER_ASC) {
      paramName
      type
      required
      defaultValue
      defaultUnits
      description
    }
  }
}
