query missions($providerId: String!, $missionTplId: String!) {
  allMissionsList(condition: {
    providerId: $providerId
    missionTplId: $missionTplId
  }) {
    providerId
    missionTplId
    missionId
    missionStatus
    assetId
    description
    startDate
    endDate
  }
}
