query mission($providerId: String!, $missionTplId: String!, $missionId: String!) {
  missionByProviderIdAndMissionTplIdAndMissionId(
    providerId: $providerId,
    missionTplId: $missionTplId,
    missionId: $missionId
  ) {
    providerId
    missionTplId
    missionId
    missionStatus
    assetId
    assetByProviderIdAndAssetId {
      className
    }
    description
    argumentsByProviderIdAndMissionTplIdAndMissionIdList {
      paramName
      paramValue
      paramUnits
      parameterByProviderIdAndMissionTplIdAndParamName {
        type
        required
        defaultValue
        description
      }
    }
    missionTplByProviderIdAndMissionTplId {
      parametersByProviderIdAndMissionTplIdList(orderBy: PARAM_ORDER_ASC) {
        paramName
        type
        required
        defaultValue
        defaultUnits
        description
      }
    }
  }
}
